---
- name: Private subnet
  hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
      - group_vars/private-subnet.yml
  vars:
      security_group: "{{ security_groupname }}"
      region: "{{ region_name }}"
      gpname: "{{ IAM_groupname }}"
      keypair: "{{ keypair_name }}"
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key ]}"
  tasks:
    - name: associate subnet to the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc_id }}"
        region: "{{ region_name }}"
        cidr: "{{ cidr }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        resource_tags:
            Name: "{{ Private_Subnet_name }}"
      register: subnet
