---
securitygroup: ansible
region_name: ap-south-1
IAM_groupname: IAM group name
keypair_name: key name
access_key: access key
secret_key: secret key 
cidr: 10.22.0.0/16
requestor_name: requestor name
env_name: DEV
resource_name: VPC-TWO-TIER-APPLICATION
back_up: NA
business_hours: EST 00-00
automate: OPT OUT
owner: mail address
cost_center_name: CLOUD
customer_name: customer name
