- name: provision an Application server Ec2 Instance
  hosts: localhost
  connection: local
  tags: provisioning
  vars_files:
      - group_vars/app-ec2.yml
  vars:
      instance_type: t2.micro
      image: ami-5b673c34
      security_group: app-server-security-group
      region: ap-south-1
      gpname: "{{ IAM_groupname }}"
      keypair: "{{ keypair_name }}"
      state: present
      number: 1
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
  tasks:
    - name: Create Application Server instance
      ec2:
         group: "{{ security_group }}"
         instance_type: "{{instance_type}}"
         image: "{{image}}"
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"
         region: "{{region}}"
         wait: true
         exact_count: "{{number}}"
         count_tag:
           Name: "{{gpname}}"
         instance_tags:
              Name: "{{ instance_name }}"
         group_id: "{{ group_id }}"
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         key_name: "{{keypair}}"
      register: ec2
