---
- name: provision an Database Server Ec2 Instance
  hosts: localhost
  connection: local
  tags: provisioning
  vars:
      instance_type: t2.micro
      image: ami-5b673c34
      security_group: app-server
      region: ap-south-1
      gpname: groupname
      keypair: keypair name
      state: present
      number: 1
      aws_access_key: your aws access key
      aws_secret_key: your aws secret access key
  tasks:
    - name: Create Database server Intsance
      ec2:
         group: "{{ security_group }}"
         instance_type: "{{instance_type}}"
         image: "{{image}}"
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"
         region: "{{region}}"
         wait: true
         exact_count: "{{number}}"
         count_tag:
           Name: "{{gpname}}" 
         instance_tags:
              Name: "{{ instance_name }}"
         vpc_subnet_id: your private subnet_id
         key_name: "{{keypair}}"
      register: ec2

                   
