---
- name: setup NAT gateway
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
      security_group: ansible
      region: ap-south-1
      gpname: groupname
      keypair: keypairname
      aws_access_key: your aws access key
      aws_secret_key: your aws secret access key
  tasks:
    - name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
      ec2_vpc_nat_gateway:
        state: present
        subnet_id: subnet id of public (check this before executing)
        wait: yes
        region: ap-south-1
        if_exist_do_not_create: true
      register: new_nat_gateway
