---
- name: Private subnet
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
      security_group: ansible
      region: ap-south-1
      gpname: EC2Admin
      keypair: ansible
      aws_access_key: AKIAJCIL4HV3EJ5DN3QQ
      aws_secret_key: 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
  tasks:
    - name: associate subnet to the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc-04d22970ca8dca51c
        region: ap-south-1
        cidr: 10.22.1.0/24
        aws_access_key: AKIAJCIL4HV3EJ5DN3QQ
        aws_secret_key: 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
        resource_tags:
            Name: Private_Subnet_Databaseserver
      register: subnet
