---
- name: Private subnet
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
      security_group: ansible
      region: ap-south-1
      gpname: groupname
      keypair: keypairname
      aws_access_key: your aws access key
      aws_secret_key: your aws secret access key
  tasks:
    - name: associate subnet to the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc id
        region: ap-south-1
        cidr: 10.22.1.0/24
        aws_access_key: your aws access key
        aws_secret_key: your aws secret access key
        resource_tags:
            Name: Private_Subnet_Databaseserver
      register: subnet
