---
- name: Public Subnet
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
      security_group: security group name
      region: ap-south-1
      gpname: groupname
      keypair: keypair name
      aws_access_key: your aws access key
      aws_secret_key: your aws secret access key
  tasks:
    - name: associate subnet to the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: vpc id
        region: ap-south-1
        cidr: 10.22.0.0/24
        aws_access_key: your aws access key
        aws_secret_key: your aws secret access key
        map_public: yes
        resource_tags:
            Name: Public_Subnet_Applicationserver
      register: subnet
    - name: create IGW
      ec2_vpc_igw:
        vpc_id: vpc id
        region: ap-south-1
        aws_access_key: your aws access key
        aws_secret_key: your aws secret access key
        state: "present"
        tags:
           Name: internet_gateway
      register: igw
