---
- name: Route IGW
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
      region: ap-south-1
      gpname: EC2Admin
      keypair: ansible
  tasks:
    - name: route IGW
      ec2_vpc_route_table:
        vpc_id: vpc-04b0b0fcf2817a2aa
        region: ap-south-1
        aws_access_key: AKIAJCIL4HV3EJ5DN3QQ
        aws_secret_key: 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
        subnets: subnet-0fce8f3ebf4ddd8a5
        routes: 
          - dest: 0.0.0.0/0
            gateway_id: igw-026825d17b4db5848
        tags:
          Name: networktest-route
    #update the CIDR address in the SSH port section
    - name: Create security group
      ec2_group: 
        name: app-server
        description: App-Server security group
        vpc_id: vpc-04b0b0fcf2817a2aa
        region: ap-south-1
        aws_access_key: AKIAJCIL4HV3EJ5DN3QQ
        aws_secret_key: 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
        rules:
          - proto: tcp
            ports: 
            - 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
      register: security_group
