---
- name: setup vpc
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
      security_group: ansible
      region: ap-south-1
      gpname: groupname
      keypair: keypairname
      aws_access_key: your aws access key
      aws_secret_key: your aws secret access key
  tasks:
    - name: create VPC 
      ec2_vpc_net:
        name: networktest-vpc
        state: present
        region: ap-south-1
        cidr_block: 10.22.0.0/16
        aws_access_key: your aws access key
        aws_secret_key: your aws secret access key
      register: vpc

