---
- name: associate subnet to the VPC
  ec2_vpc_subnet:
        state: present
        vpc_id: vpc-00524a5dd45993301
        region: ap-south-1
        cidr: 10.22.1.0/24
        aws_access_key: AKIAJCIL4HV3EJ5DN3QQ
        aws_secret_key: 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
        resource_tags:
            Name: Private_Subnet_Databaseserver
  register: subnet
