- name: provision an Application server Ec2 Instance
  hosts: localhost
  connection: local
  tags: provisioning
  vars_files:
      - group_vars/app-ec2.yml
  vars:
      instance_type: t2.micro
      image: ami-5b673c34
      security_group: app-server-security-group
      region: ap-south-1
      gpname: "{{ IAM_groupname }}"
      keypair: "{{ keypair_name }}"
      state: present
      number: 1
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      aws_tags:
         NAME: "{{ requestor_name }}"
         ENVIRONMENT: "{{ env_name }}"
         RESOURCE ID: "{{ resource_name }}"
         BACK UP: "{{ back_up }}"
         BUSINESS HOURS: "{{ business_hours }}"
         AUTOMATE: "{{ automate }}"
         OWNER: "{{ owner }}"
         COST CENTER: "{{ cost_center_name }}"
         CUSTOMER: "{{ customer_name }}"
  tasks:
    - name: Create Application Server instance
      ec2:
         group: "{{ security_group }}"
         instance_type: "{{instance_type}}"
         image: "{{image}}"
         aws_access_key: "{{aws_access_key}}"
         aws_secret_key: "{{aws_secret_key}}"
         region: "{{region}}"
         wait: true
         exact_count: "{{number}}"
         count_tag:
           Name: "{{gpname}}"
         instance_tags: "{{ aws_tags }}"
         group_id: "{{ group_id }}"
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         key_name: "{{keypair}}"
      register: ec2_result

    - debug:
        msg: "app-server  public ip address is: {{ec2_result.instances[0].public_ip}}"

    - name: wait for ssh to come up
      local_action: wait_for
                    host={{ec2_result.instances[0].public_ip}}
                    port=22
                    state=started
      with_items: ec2.instances

#    - name: connecting to bastion host
#      command: ssh -i yourkey.pem ec2-user@bastion host ip
