---
- name: Private subnet
  hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
      - group_vars/private-subnet.yml
  vars:
      security_group: "{{ security_group_name }}"
      region: "{{ region_name }}"
      gpname: "{{ IAM_groupname }}"
      keypair: "{{ keypair_name }}"
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key ]}"
  tasks:
    - name: associate subnet to the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc_id }}"
        region: "{{ region_name }}"
        cidr: "{{ cidr }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        resource_tags:
          NAME: "{{ requestor_name }}"
          ENVIRONMENT: "{{ env_name }}"
          RESOURCE ID: "{{ resource_name }}"
          BACK UP: "{{ back_up }}"
          BUSINESS HOURS: "{{ business_hours }}"
          AUTOMATE: "{{ automate }}"
          OWNER: "{{ owner }}"
          COST CENTER: "{{ cost_center_name }}"
          CUSTOMER: "{{ customer_name }}"
      register: privatesubnet

    - debug:
         msg: "private subnet id is: {{privatesubnet.subnet.id}}"

    - name: Create security group
      ec2_group:
        name: "{{ security_group }}"
        description: security group for db servers
        vpc_id: "{{ vpc_id }}"
        region: "{{ region_name }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
      register: privatesg

    - debug:
         msg: "security group id for private subnet is: {{privatesg.group_id}}"

